document.addEventListener('DOMContentLoaded', () => {
    const agentGrid = document.getElementById('agentGrid');
    let selectedAgent = '';

    // Simulated list of agents - this would be generated by your server
    const agents = ['Astra', 'Breach', 'Brimstone']; // Add all agent names here

    // Function to create agent elements
    const loadAgents = () => {
        agents.forEach(agentName => {
            const agentElem = document.createElement('img');
            agentElem.src = `agents/${agentName}/${agentName}.png`; // Path to the agent's image
            agentElem.alt = agentName;
            agentElem.classList.add('agent');
            agentElem.addEventListener('click', () => selectAgent(agentName));
            agentGrid.appendChild(agentElem);
        });
    };

    // Function to handle agent selection
    const selectAgent = (name) => {
        if(selectedAgent) {
            const prevSelectedElem = document.querySelector('.agent.selected');
            if(prevSelectedElem) {
                prevSelectedElem.classList.remove('selected');
            }
        }
        selectedAgent = name;
        const selectedElem = document.querySelector(`img[alt="${name}"]`);
        selectedElem.classList.add('selected');
    };

    // Load the agents into the grid
    loadAgents();
});
